modLoader="javafml"
loaderVersion="[47,)"
license="GPL-3.0"

[[dependencies.cduutils]]
    modId="forge"
    mandatory=true
    versionRange="[47.4.0,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.cduutils]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="CLIENT"

[[mods]]
    modId="cduutils"
    version="1.0.0"
    displayName="CDU-Utilities"
    description="Allows you to easily see the stats of a player in-game."
